sudo: false
language: java
notifications:
  email: false
  irc:
    channels:
    - irc.esper.net#MyTown
    template:
    - "%{repository_name} (%{branch}): %{commit_message} - %{author}"
    - 'Result: %{result}'
    - 'Change view: %{compare_url}'
    - 'Build details: %{build_url}'
cache:
  directories:
  - "$HOME/.gradle/caches/"
deploy:
  - provider: releases
    api_key:
      secure: MpSeWjUxKrPIpuoDhb6OUqL1fJXixEi8vOMXn8NCVKQqFo016Vr2fB8rhwVJwb0YSlmvGmLnNNYcuAmJ8GQ8acIxWSg4oG22M2Ob9URB7h7dgFGMyoObvoLNdSwDjw5h/Lxea+thnlpelSM35J/o/VZVhPC9HzwnJlSRwyIWZyw=
    file: build/libs/*
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      repo: MyEssentials/MyEssentials-Core
      all_branches: true
  - provider: script
    script: gradle curse
    on:
      tags: true
      repo: MyEssentials/MyEssentials-Core
      all_branches: true
    
